.github/workflows/mkdocs.yaml, docs/architecture/backend.md, docs/architecture/frontend.md, docs/architecture/overview.md, docs/index.md, docs/requirements.md, go.mod, mkdocs.yaml
solves the following issue:
- #2
=> add docs files and workflow for mkdocs deployment

.github/workflows/ci.yaml, .github/workflows/lint.yaml
small change for renaming some workflows:
- lint
- ci
=> renaming lint and ci workflows

test/fizzbuzz/fizzbuzz_test.go
=> move test cases key name to description

build/package/fizzbuzz/Dockerfile
add pending dockerfile for fizzbuzz to the build dir
=> add Dockerfile for fizzbuzz

docs/requirements.md
add documentation for pre-commit & local deployment
=> 15: update requirements documentation

pkg/fizzbuzz/fizzbuzz.go
improve the fizzbuzz algorithm, make it more efficient.
=> 18: improve fizzbuzz algorithm

.github/workflows/release.yaml, docker-compose.yaml
=> extend docker release

docs/create-users.md, docs/getting-started.md, mkdocs.yaml
=> improve docs

.github/workflows/release.yaml
=> rename docker images

.github/workflows/release.yaml
=> fix docker image name

docker-compose.yaml, docs/getting-started.md
use docker volumes instead of mounting to actual directory
=> fix: docker-compose volume configuration

.pre-commit-config.yaml, ui/app/general/buttons/StyledButton.tsx, ui/app/general/forms/InputField.tsx, ui/app/general/forms/TextAreaField.tsx, ui/app/general/modals/PopUpModal.tsx, ui/app/habits/HabitForm.tsx, ui/app/habits/NewHabit.tsx, ui/app/habits/habitcard.tsx, ui/app/layout.tsx, ui/app/page.tsx, ui/lib/design.ts, ui/package.json, ui/postcss.config.js, ui/styles/globals.css, ui/tailwind.config.js, ui/yarn.lock
solves the following issue:
- #50
=> 50 UI create a habit

docs/getting-started.md, docs/project/impediment-backlog.md, docs/project/project-decisions.md, docs/project/project-setup.md, mkdocs.yaml
resolves the following issue:
- #85
=> docs: add db docs, add first draft for project documentation

ui/.dockerignore, ui/Dockerfile, ui/app/page.tsx
add ui Dockerfile and get it working
=> add ui Dockerfile

ui/components/habits/HabitCard.tsx
=> add journal entry

ui/components/habits/HabitCard.tsx, ui/components/journalEntry/JournalEntryCard.tsx, ui/components/journalEntry/JournalEntryForm.tsx
Implements:
- #56 
- #57 
- #138
- #139
- #140
- #141
Update Figma:
Update Implemented:
Delete Figma:
Delete Implemented:
=> update and delete journal entry

ui/components/general/forms/Select.tsx, ui/components/habits/HabitForm.tsx, ui/components/journalEntry/JournalEntryForm.tsx
Basic select dropdown that we can use later
=> Add select component

ui/components/Layout.tsx, ui/components/general/Nav.tsx, ui/components/general/modals/PopUpModal.tsx
fixing pop up modal at mobile scale
=> fix: pop up modal at mobile scale

build/package/habits/Dockerfile.m1, docker-compose-m1.yaml, src/main/kotlin/ch/bfh/habits/WebConfig.kt, ui/components/habits/HabitForm.tsx, ui/components/journalEntry/JournalEntryCard.tsx, ui/components/journalEntry/JournalEntryForm.tsx, ui/pages/journal.tsx
solves the following issue(s):
- #151
=> 151 better input validation

ui/components/general/Nav.tsx, ui/components/general/forms/Select.tsx, ui/components/habits/HabitForm.tsx, ui/components/journalEntry/JournalEntryForm.tsx
solves the following issue(s):
- #150
=> feat: integrate select component

ui/components/journalEntry/JournalEntryCard.tsx, ui/components/journalEntry/JournalEntryForm.tsx, ui/lib/interfaces.ts
=> Fix journal creation

README.md
=> fix: readme codefactor

.github/workflows/pr-labels.yaml, ui/pages/profile.tsx
logout button and profile user information display
=> 169 provide a way to login and logout

src/feature-test/kotlin/ch/bfh/habits/auth/AuthCrudActor.kt, src/feature-test/kotlin/ch/bfh/habits/auth/impl/WebClientBasedAuthCrudActor.kt, src/feature-test/kotlin/ch/bfh/habits/base/BaseCrudActor.kt, src/feature-test/kotlin/ch/bfh/habits/base/impl/WebClientBasedBaseCrudActor.kt, src/feature-test/kotlin/ch/bfh/habits/habit/HabitCrudActor.kt, src/feature-test/kotlin/ch/bfh/habits/habit/HabitCrudFeatureTests.kt, src/feature-test/kotlin/ch/bfh/habits/habit/HabitTestConfiguration.kt, src/feature-test/kotlin/ch/bfh/habits/habit/impl/WebClientBasedHabitCrudActor.kt, src/feature-test/kotlin/ch/bfh/habits/journalentry/JournalEntryCrudActor.kt, src/feature-test/kotlin/ch/bfh/habits/journalentry/JournalEntryCrudFeatureTests.kt, src/feature-test/kotlin/ch/bfh/habits/journalentry/JournalEntryTestConfiguration.kt, src/feature-test/kotlin/ch/bfh/habits/journalentry/impl/WebClientBasedJournalEntryCrudActor.kt, src/main/kotlin/ch/bfh/habits/controllers/AuthController.kt, src/main/kotlin/ch/bfh/habits/controllers/JournalEntryController.kt, src/main/kotlin/ch/bfh/habits/filters/JwtRequestFilter.kt, src/main/kotlin/ch/bfh/habits/services/HabitService.kt, src/main/kotlin/ch/bfh/habits/services/JournalEntryService.kt, src/main/kotlin/ch/bfh/habits/util/TokenProvider.kt, src/test/kotlin/ch/bfh/habits/controllers/HabitControllerTests.kt, src/test/kotlin/ch/bfh/habits/controllers/JournalEntryControllerTests.kt, src/test/kotlin/ch/bfh/habits/services/HabitServiceTest.kt, src/test/kotlin/ch/bfh/habits/services/JournalEntryServiceTest.kt
More test to be added later. Just test what makes sense
=> Fix all unit tests

ui/components/habits/HabitCard.tsx, ui/components/habits/HabitForm.tsx, ui/pages/info.tsx
=> 168 show a score for each habit based on the frequency goal

README.md, mkdocs.yaml
=> docs: remove codefactor

mkdocs.yaml
=> docs: change color to white

mkdocs.yaml
=> fix: accent

ui/components/habits/HabitCard.tsx, ui/context/userContext.tsx, ui/next.config.js, ui/package.json, ui/pages/_app.tsx, ui/yarn.lock
=> fix: length of journalentries

ui/components/Loading.tsx, ui/components/general/Nav.tsx
=> feat: improve routing
